# Generated by Django 5.1.1 on 2025-03-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutorunEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('detected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ip', models.GenericIPAddressField()),
                ('local_port', models.IntegerField()),
                ('remote_ip', models.GenericIPAddressField()),
                ('remote_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('detected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pid', models.IntegerField()),
                ('path', models.TextField()),
                ('hash_value', models.CharField(blank=True, max_length=64, null=True)),
                ('detected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistryKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('detected', models.BooleanField(default=False)),
            ],
        ),
    ]
