# Generated by Django 5.1.1 on 2025-03-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
