# Generated by Django 5.1.1 on 2025-03-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunting', '0002_alter_process_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconnection',
            name='remote_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
