# Generated by Django 5.1.1 on 2025-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunting', '0003_alter_networkconnection_remote_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkconnection',
            name='remote_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
