# Generated by Django 5.1.1 on 2025-03-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunting', '0004_alter_networkconnection_remote_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(choices=[('process', 'Process'), ('ip', 'IP Address')], max_length=20)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
